### ISSUE TITLE
add type annotations (typescript or flowtype)

### ISSUE THREAD

**Issue by vutran** [vutran/dext#10]
open for discussion on what to use. ideally creating a definition file for TypeScript in the `dext-core-utils` repo could be a great start for us.

**Comment by adnasa** [comment]
I don't think this is necessary at all, IMO

**Comment by adnasa** [comment]
Is this still necessary?

**Comment by vutran** [comment]
> Is this still necessary?

Nope. Let's stick to vanilla ES. No reason to add another layer of complexity by transpiling.

**Comment by adnasa** [comment]
I know right, @vutran 😉
