### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by zeke** [vutran/dext#116]
Just came across Dext. Such a cool project. I'm a long-time Quicksilver/Alfred/Spotlight user, so an extensible Electron app inspired by these concepts really appeals to me. :)

I would love to see this on the Electron website. @vutran would you care to open a pull request?

https://github.com/electron/electron.atom.io/blob/gh-pages/CONTRIBUTING.md#adding-an-app-or-project-to-the-site

**Comment by vutran** [comment]
Hi @zeke, thanks for the kind words! Definitely sounds good. I'm still working on a logo/icon/site for Dext so I have been holding out till that is done before opening a PR.

**Comment by zeke** [comment]
> working on a logo/icon/site

:+1:

**Comment by vutran** [comment]
@zeke Officially submitted! 🎉

**Comment by vutran** [comment]
😎

**Comment by zeke** [comment]
💃
