### ISSUE TITLE
Creating Packages

### ISSUE THREAD

**Issue by z3t0** [vutran/dext#118]
Hi,

So I am trying to create a [plugin](https://github.com/z3t0/dext-term-plugin) for dext and have a few questions.

1. How do i get dext-cli to detect my plugin? I have published it to [npm](https://www.npmjs.com/package/dext-term-plugin) but it doesn't show up when doing `dpm s term`
2. Is there a more efficient way to develop plugins? That is without republishing each time? I know that there's npm link, does dpm link work the same way?

**Comment by vutran** [comment]
> How do i get dext-cli to detect my plugin? I have published it to npm but it doesn't show up when doing `dpm s term`

Your plugin's `package.json` should contain a `dext-theme` or `dext-plugin` in the `keywords` list. ([see here](https://github.com/vutran/dext-core-utils/blob/develop/src/utils/search.js#L9))

> Is there a more efficient way to develop plugins? That is without republishing each time? I know that there's npm link, does dpm link work the same way?

The best method for dev is to use `dpm link` and `dpm unlink`. It works like `npm link` and `npm unlink`. This will allow you to easily create symlinks from your working project's directory to the `~/.dext/plugins` directory. The command will also automatically add/remove the plugin in the `~/.dext/config.json` file.

**Comment by z3t0** [comment]
Okay so I am trying to understand how I can adapt `action` to do something. Lets say instead of one of the options provided, I'd like the plugin to execute a function, I can't seem to figure out how that is done

**Comment by vutran** [comment]
You can use the `exec` action which will spawn a child process. See how we did this on the [screensaver plugin](https://github.com/vutran/dext/tree/develop/resources/plugins/screensaver).

**Comment by z3t0** [comment]
Okay but that may not be ideal since it doesn't allow arguments to be passed along? I've made a modification that allows that and will commit after some more testing

**Comment by vutran** [comment]
@z3t0 `exec` actions currently doesn't support sending extra args to the new process but this would be a great addition. I'd like to see how you solve your issue when it's ready and perhaps we can merge it into core? Open for thoughts.

**Comment by z3t0** [comment]
This has been answered
