### ISSUE TITLE
Dext only sees web history

### ISSUE THREAD

**Issue by Tattomoosa** [vutran/dext#122]
I downloaded the app. Running Sierra on a mid-2010 macbook pro. My web history from chrome shows up when I search but no applications or files/folders.

**Comment by vutran** [comment]
We currently don't have a plugin to fetch app results at the moment but it is in my todo list. I am open for a PR if you want to contribute towards making app discovery available.

**Comment by z3t0** [comment]
> my todo list

Is there a todo list somewhere i could start working on?

**Comment by vutran** [comment]
> Is there a todo list somewhere i could start working on?

Not publicly available at the moment. I'll see to get these added into the Projects tab this week.

**Comment by vutran** [comment]
Closing this as the issue has been answered.
