### ISSUE TITLE
[Question] execute command immediately after entered keyword (no need to specify query)

### ISSUE THREAD

**Issue by brpaz** [vutran/dext#133]
Hello. 
Its possible to run a command in dext immediately after typing the keyword without the need to enter any search query.

Ex: I am writing a plugin to display current IP address information. I just want to type "IP" and get the results immediately, without entering any search query.

**Comment by vutran** [comment]
@brpaz, only core plugins can allow querying without the keyword. This is more to prevent an event where everyone makes a plugin that requires no keyword. I'm open for discussions on removing that restrictions for 3rd party plugins.

On a side note, you can look up plugin helper items. Helpers are displayed when the keyword is typed but not query is found. These are used for tips but can be used for displaying your data.

**Comment by brpaz** [comment]
yes. I thought about using using the helper function. Will give it a try, but I can only display one item right?
Still, I think I can rewrite my IP plugin a bit to receive a search query, like "ip info", that could allow more options in the future.
I think all the other plugins I want to build allays need a search query.

Thank you.

**Comment by vutran** [comment]
Correct, we are currently limited to 1 helper item but open for allowing multiple items to be returned if needed.

The lines where this is handled can be found [here](https://github.com/vutran/dext/blob/develop/app/main/plugins.js) at `queryHelper`. Feel free to submit a PR but we would want to present backwards compatibility to allow a single item or an array of items. 👍

**Comment by brpaz** [comment]
Thanks to #137 its now possible to use Helper items to mimic this functionality. 
It will be enough for me atm.

In the future, maybe we can discuss adding actions to helper items to make this even more complete.
