### ISSUE TITLE
Hide from the dock and add context menu

### ISSUE THREAD

**Issue by akz92** [vutran/dext#151]
I believe that the app shouldn't appear on the dock and on the application switcher, like other apps of this kind. Besides that, it would be good to have a Context Menu on the Tray to provide a couple options like toggle and quit. Have you already discussed this?

I implemented this in [my fork](https://github.com/akz92/dext), if you want to take a look.

**Comment by vutran** [comment]
@akz92 Those are great commits. Can you send a PR for them?

**Comment by akz92** [comment]
Sure!
