### ISSUE TITLE
getting disabled plugins

### ISSUE THREAD

**Issue by mrjohnyhats** [vutran/dext#159]
Hi,

I'm trying to make a small settings window for Dext, but this is my first project with electron and react so I might not be submitting a pull request for a week or two (currently a student working on this a little each day). One thing I wanted to implement is a checklist of every plugin in the` ~/.dext/plugins` path, but I noticed that `dext-core-utils` doesn't have a method for listing disabled functions. I know I could technically just go to the plugins path and just go through every folder, but I was wondering if I could just add a new item to the conf that would include disabled functions, or implement another method in `dext-core-utils`. If you're cool with it, I can make my own branch of `dext-core-utils` and submit a pull request on that repo.

**Comment by vutran** [comment]
Can you clarify what you mean by disabling functions?

**Comment by mrjohnyhats** [comment]
oops, meant a function that would fetch a list of all plugins in the directory instead of just the disabled ones

**Comment by vutran** [comment]
Ah I see. I thought we had that already in `dext-core-utils` but I guess it's not there. Go ahead and give it a shot. Let me know if you have any questions or any difficulties. 👍

**Comment by vutran** [comment]
This is now resolved in https://github.com/vutran/dext-core-utils/pull/47
