### ISSUE TITLE
Allow app window to be sharp or rounded edges

### ISSUE THREAD

**Issue by vutran** [vutran/dext#16]
Some people just prefer sharp corners.

**Comment by arthur801031** [comment]
@vutran  May I work on this?  I'm a first time contributor to dext.

**Comment by vutran** [comment]
Sure, go ahead. 👍

**Comment by arthur801031** [comment]
@vutran  I've tried changing the borderRadius attribute in 'app/renderer/src/components/App.js', but it didn't affect the window's edges. Are the edges round because of the operating system's default setting? If so, how do we change it? Thank you!

**Comment by vutran** [comment]
@arthur801031 I thought the same. It may be an operating system issue limitation. The only way I can actually see us achieving sharp edges is to allow transparent windows via Electron, and build the rounded edges as an HTML container.

**Comment by arthur801031** [comment]
@vutran  I'm not familiar with Electron. How should we go about doing this? Could you please provide some guidance? Thank you!

**Comment by vutran** [comment]
Sure, I'll see if I can outline something out for you in the next few days as I'm quite busy at the moment.

**Comment by W0lfw00d** [comment]
Haven't tried it yet but it seems to be a setting of the browser window:
```
const BrowserWindow = require('electron').BrowserWindow;
myWindow = new BrowserWindow({
    name: "My app window",
    width: 500,
    height: 250,
    transparent: true,
    frame: false,
    toolbar: false
});
'```

https://github.com/electron/electron/blob/master/docs/api/frameless-window.md

**Comment by vutran** [comment]
To add to @W0lfw00d comment, you would also want make the window transparent. Then, we can use CSS to create a white background container and handle adding or excluding the border-radius with pure CSS.

**Comment by arthur801031** [comment]
@vutran  @W0lfw00d  I tried adding `transparent: true,` to BrowserWindow's options in index.js, but it had no effect on the color or look of the window.

**Comment by vutran** [comment]
@arthur801031 Try modifying the `<body>` background color to transparent, then make the app container colored with a border radius. Though I'm not sure if this would actually resolve the issue as I never really tried transparent windows yet.

**Comment by arthur801031** [comment]
@vutran  I got it to work now! 
<img width="774" alt="screen shot 2016-11-11 at 3 06 26 pm" src="https://cloud.githubusercontent.com/assets/4562118/20207190/7aa0f7f0-a820-11e6-9b6e-10da18dc5979.png">

I didn't modify the `<body>` background color. It didn't work because the app container's width was 100%, so the sharp edges were covered by the window even though it was transparent. Therefore, I set app container's width to 99% and used margin-left to move the container toward center. 

I'm not sure where to put the option to toggle sharp corners on or off. Please let me know. Thank you!

**Comment by vutran** [comment]
I just tried it out and it works perfectly! Also applied a `borderRadius` in a custom theme and it works as well.

Thanks for the awesome PR @arthur801031 !
