### ISSUE TITLE
Core plugin calculator returns functions upon specific queries

### ISSUE THREAD

**Issue by justinpchang** [vutran/dext#174]
The calculator plugin queries the math.js library. Sometimes, as is the case with the queries 'help' or 'random', the math.js library returns a function instead of an error, so the function code is displayed because of the `.toString()` in line 12 of the index.js file of the calculator plugin.

I am unsure of how to submit a pull request to fix this bug, however a possible quick fix for this could be adding the below code after line 18 of the index.js file of the calculator:

`if(typeof ans === 'function') {
        throw 'function returned';
}`

This should not break any other results because valid results are of types number or object.

Hope this helps.

**Comment by vutran** [comment]
Solved in #175
