### ISSUE TITLE
have dedicated folders for modules

### ISSUE THREAD

**Issue by adnasa** [vutran/dext#189]
At the moment we have the following folder structure

```
- __mocks__
  - any mock
- __tests__
  - app
    - main
      - actions
        - copy.js
- src
  - app
    - main
      - actions
        - copy.js
```

Although it is not wrong, it is rather inflexible;

1. we would have to look into the different folders just to have a clear view on the coverage of the component or module (such as test, any README file, or styles etc..)
2. moving a file, means moving two different files for two different context given the example above (e.g `__tests__` is a context for `copy.js)

#### Proposal for a new set up would be the following

With the following setup:

```
- src
  - app
    - main
      - actions
        - index.js // for export purposes
        - copy.js
        - copy.spec.js
```

This would mean that `removing a module = removing a folder`, and `moving a module = moving a folder`, the only thing that change is context.
This also means `one module = test + main file + export file`.

---

Where do we put `__mocks__`?

Here is where I don't have a strong opinion.  The issue I find is that we are using a `__mocks__` folder to store our mocks, although the mock itself could have been used only once across the entire application test suit. For these situtation, I would have rather seen the mock to be inline with the test itself.

**Comment by vutran** [comment]
This makes sense.

`jest`'s mock system is a bit weird. If I remember correctly, the root `__mocks__` directory usually store mocks for `node_modules`. For local modules, a `__mocks__` directory should be located alongside the file it is trying to mock.

## Example:

```
- src
  - utils
    - __mocks__
      - foo.js
    - foo.js
    - foo.spec.js
```

**Comment by adnasa** [comment]
> For local modules, a __mocks__ directory should be located alongside the file it is trying to mock.

yeah absolutely, this makes sense of course, but we're going to have to decide as we do the migration.

Imagine the following on a larger scale

```
src
  a
    a.spec.js
    a.js
  b
    b.spec.js
    b.js
another-folder
  c
    c.spec.js
    c.js
```

Given `a` and `b` requiring `c`, with your suggestion, where do we mock `c`? 😄
root folder of `src`? I'm asking because I don't have any extensive experience of putting mocks inside a `__mocks__` folder. only inline-mocking (with jest even). Maybe the example above works 😄

**Comment by adnasa** [comment]
I will close this now, since I'm pretty happy that we moved all the `.spec.js` files.
As for missing tests on components and other utilities, let's pick this up later.

Thanks for all the reviews!
😉
