### ISSUE TITLE
have redux-saga removed

### ISSUE THREAD

**Issue by adnasa** [vutran/dext#191]
At the moment we are using `redux-saga`  as part of the state-management. This shouldn't be needed since the data-flow within the `dext` itself is pretty straight forward.

we can even go as far as to consider having `redux` removed.

There are some strong points where redux would shine in a smaller application like `dext` but they wouldn't outweigh simplicity nor attempt to just use `React`'s own recommended patterns.

---

#### something to consider

In fact, IMO using the new Context API would be the perfect tool for us to leverage for our use case, such as UI configuration, in conjunction with just props being passed down from one "interface" or prop-getters.

**Comment by vutran** [comment]
We decided to move forward with removing Redux for the new Context API. Let's try to get React updated to the latest version so we can get this new hotness ready for the migration.

**Comment by adnasa** [comment]
>  Let's try to get React updated to the latest version

I'm on it 😄

**Comment by adnasa** [comment]
One cool thing about using `context` here would be to eliminate imports of `ipcRenderer`,
which essentially means that we leak `electron` functionality into our components.

Admittedly, I have yet to try out the new Context API, but even with the old approach, you could see the benefit

```js
class A extends React.Component {
  getChildContext () {
    return {
      socket: ipcRenderer,
    }
  }
}

class B extends React.Component {
  static contextTypes = {
    // because `context`, `socket` doesn't have to interface `ipcRenderer`
    socket: PropTypes.shape({
      on: PropTypes.function.isRequired,
    })
  }
}

// unit-test
// mock all the things..
const view = shallow(
  <B {...props} />,
  {
    socket: {
      on: jest.fn()
    }
  }
)
```

**Comment by himanshuchauhan** [comment]
Can I start working on this? Anything essential I need to know before working on this?

**Comment by vutran** [comment]
> Can I start working on this? Anything essential I need to know before working on this?

@himanshuchauhan Definitely. Let's try to keep the PR small since it's a huge migration. Ideally, we can move one state at a time. Please refer to PR #206 for an example of what we previously did. Let us know if you have any other questions.

Thanks!

**Comment by adnasa** [comment]
> Let's try to get React updated to the latest version

https://github.com/DextApp/dext/pull/211 🔥

**Comment by adnasa** [comment]
🚀
