### ISSUE TITLE
add test for `utils/conf`

### ISSUE THREAD

**Issue by adnasa** [vutran/dext#197]

**Comment by vutran** [comment]
We should merge `utils/conf` and `utils/CacheConf`, maybe even remove it in favor of a single conf. The additional layers makes it confusing.

**Comment by vutran** [comment]
History: `utils/CacheConf` was originally extracted from one of Sindre's pkg which has it's own pkg now [here](https://github.com/samverschueren/cache-conf).

**Comment by adnasa** [comment]
Sure, I'll merge them

**Comment by adnasa** [comment]
okay, not sure if I'm going to look to it anytime soon.
I'll close the other ticket, that's what I meant with "merge" 😇

**Comment by vutran** [comment]
I'm taking a look at this one.

**Comment by adnasa** [comment]
🚀
