### ISSUE TITLE
RFC: remove `app/renderer/src/schema`

### ISSUE THREAD

**Issue by adnasa** [vutran/dext#202]
So for the moment we do have some "schema" defined under `app/renderer/src/schema`.

Al though there isn't anything inherently wrong with this, it is fragile, inflexible and a bit of an overkill. There are a couple of questions that opens up with this:

- what's the origin of the props?
- `ResultItemSchema` is used once, does it need its own file?
- `ThemeSchema` is set __once__, does the "schema" need to places on each prop type validation?

---

I would want to suggest to have them remove for the reasons pointed above (point 1 and point 2) along with the reason that `ThemeSchema` or `theme` prop is for most of the part a pass-through prop.

Components with the tree of `dext`, that uses pieces of `ThemeSchema` uses just that; __a piece__.

Not to mention that with an imported `PropType.shape`, `eslint` actually (in my experience) doesn't catch up any missed prop. e.g:

```js
// theme-schema.js
PropTypes.shape({
  color: PropTypes.string.isRequired,      
})

// magento-component.js
import ThemeSchema from './theme-schema'
class A extends React.Component {
  static propTypes = {
    theme: ThemeSchema,
  }
  render () {
    // `backgroundColor` is not defined in a the "schema",
    // but the "schema" is actually "hidden" behind an import,
    // and not part of the component definition, which makes it hard for `eslint` to catch
    return <div>{this.props.backgroundColor}</div>
  }
}

ref: https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/default-props-match-prop-types.js
```

Since some components just uses a "piece" of the schema, let the concerning component define the prop-type definition for it

```js
// magento-component.js
class Magneto extends React.Component {
  static propTypes = {
    theme: PropTypes.shape({
      backgroundColor: PropTypes.string,
    }),
  }
  render () {
    return <ResultList
      // pass the entire theme to the child
      theme={this.props.theme}
    >
      // we only use `backgroundColor` in our Magneto component
      // so only this prop needs to be validated.
      {this.props.backgroundColor}
    </ResultList>
  }
}
```

**Comment by vutran** [comment]
I like this idea. +1

**Comment by vutran** [comment]
Donzo.
