### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by aharris88** [vutran/dext#21]
I installed dext with `npm install dext -g`, and for some reason I can't get it to open. I changed the Spotlight shortcut to Alt+Cmd+Space, and I even tried restarting my mac to see if it would work. Also, I don't have Alfred or any other launcher installed.

**Comment by vutran** [comment]
Hi,

An installer is not yet available for this app. I'm still looking for contributors to help out in this area.

I have just packed the latest version from master in which you can download via the instructions [here](https://github.com/vutran/dext#install).
