### ISSUE TITLE
Add ability to change the toggle key

### ISSUE THREAD

**Issue by vutran** [vutran/dext#24]
Sometimes you already have <kbd>cmd</kbd> + <kbd>space</kbd> already registered to another app. Allow a way for the user to change their key bindings to another combination.

**Comment by adnasa** [comment]
Would this be pure configuration (as in config on file-format) or are you considering a preference menu (like every other app out there)? 😉

**Comment by vutran** [comment]
I'm open to both options. A preference window would probably make more sense if we want to target non-developers. If it's  preference window, I was considering using my [`react-jsonschema`](https://github.com/vutran/react-jsonschema) to scaffold the forms but don't want the material-ui that comes with it.
