### ISSUE TITLE
Extended Details/Panel

### ISSUE THREAD

**Issue by vutran** [vutran/dext#41]
Allow items to open an extended details/panel for displaying rich content similar to Spotlight (reference screenshot below).

May be of use for some plugins such as [`dext-giphy-plugin`](https://github.com/adnasa/dext-giphy-plugin) to display a quick view of the larger image.

<img width="652" alt="screen shot 2016-09-04 at 1 59 47 pm" src="https://cloud.githubusercontent.com/assets/1088312/18233846/04559c5c-72a8-11e6-9c04-2a146f7d1da5.png">

**Comment by adnasa** [comment]
A moment of honesty, I've never used Alfred myself. I've used QS my whole life
Don't forget to look into [QS](http://qsapp.com), we may pick some gems from that amazing app 😉

**Comment by adnasa** [comment]
This is a great idea btw

**Comment by vutran** [comment]
> Don't forget to look into QS, we may pick some gems from that amazing app 😉

I've used QS way before Alfred but open to pull some features as Dext evolves.

> I want to suggest already now that we reserve <kbd>tab</kbd> as the trigger here.

It would probably be better for <kbd>tab</kbd>to be reserved for some sort of autocompletion module so you can drill down into specific sub-commands within a plugin.

Will keep this open for discussion for the best UX.

**Comment by adnasa** [comment]
a moment of honesty: I __still__ use QS (never actually tried Alfred) :bowtie: I'm old school like that :bowtie:

**Comment by vutran** [comment]
WIP.

<img width="823" alt="screen shot 2016-09-07 at 2 51 15 pm" src="https://cloud.githubusercontent.com/assets/1088312/18329904/9d7416de-750a-11e6-924b-548dd2bc2ef2.png">

**Comment by adnasa** [comment]
whoa!
so dext allows for plugins to implement their own renderer now, right?

**Comment by vutran** [comment]
The API will be updated to allow plugins to define their own `render()` function. For now, it will probably accept an HTML string, or markdown but will hopefully allow for React components in the future.

**Comment by vutran** [comment]
This has been [merged](51f90d2c63946686d4042b5da5e18aec26e5289e) into `master`.
