### ISSUE TITLE
"Esc" key does not work in other applications while Dext is running

### ISSUE THREAD

**Issue by UltCombo** [vutran/dext#55]

**Comment by adnasa** [comment]
hello @UltCombo 
thanks for you report, but this should have been resolved already => 4ff11c4

note that this is not released yet

---

if you cloned dext, update master please :)

**Comment by UltCombo** [comment]
Oh ok, thanks!
Nice work on this app, btw. 😄

**Comment by adnasa** [comment]
@UltCombo thank you 👍 😉
