### ISSUE TITLE
Add test/spec for SELECT_ITEM reducer

### ISSUE THREAD

**Issue by vutran** [vutran/dext#80]
We need to write a spec for the reducer: `app/renderer/src/reducers/selectedIndex.js`

Test file: `__tests__/app/renderer/src/reducers/selectedIndex.js`

**Comment by walkerrandolphsmith** [comment]
@vutran I will tackle this one!

**Comment by walkerrandolphsmith** [comment]
well looks like it has already been done... :)

**Comment by walkerrandolphsmith** [comment]
I have create a pull request that writes specs for the selectedIndex reducers handling of actions with type `SELECT_ITEM` [here](https://github.com/vutran/dext/pull/84).
