### ISSUE TITLE
Add test/spec for missing action creators

### ISSUE THREAD

**Issue by vutran** [vutran/dext#81]
We need to write tests for these action creators:

 - `resetDetails()`
 - `closeDetails()`
 - `openDetails()`

Test file: `__tests__/app/renderer/src/actions/creators.js`

**Comment by walkerrandolphsmith** [comment]
I can take a stab at it. @vutran

**Comment by vutran** [comment]
@walkerrandolphsmith This has been done in #82. However, check back in a few days as I plan on creating or #hacktoberfest issues. 👍
