### ISSUE TITLE
DX: Consider using NODE_PATH

### ISSUE THREAD

**Issue by adnasa** [vutran/dext#92]
I think that it is time that we start considering setting [`NODE_PATH`](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) to set a specific folder as the source of truth for loading modules, beyond the `node_modules` folder.

The aim is to the have the following (_example_)

**before**

``` js
import paths from '../../../utils/paths'
```

**after**

``` js
import paths from 'core/utils/paths'
```

**Comment by vutran** [comment]
It looks like `NODE_PATH` was deprecated a while back.

**Comment by adnasa** [comment]
Leaving this open, until we've found a better option then.

**Comment by adnasa** [comment]
this is only thing I found discussing this issue in depth
https://github.com/nodejs/node/issues/1627#issuecomment-102186359

**Comment by vutran** [comment]
I've been thinking of this and perhaps using `webpack`'s `resolve.root` or `resolve.moduleDirectories` would work. An idea would be using the package name `dext` for absolute imports.

**before**

```js
import Button from '../../../src/components/Button.js';

**after**

```js
import Button from 'dext/app/renderer/src/components/Button.js'
```

Otherwise, we can split it based on the Electron process (main/renderer)

```js
// source: app/main/themes
import themes from 'dext-main/themes';

// source: app/renderer/src/components
// - removes the "src" from the path string (side note: to be removed in the future)
import Button from 'dext-renderer/components/Button';
```

**Comment by adnasa** [comment]
Since we are considering `lerna` when we are going to consolidate our  packages, there is no need for this right now
