### ISSUE TITLE
Copy to Clipboard Alert

### ISSUE THREAD

**Issue by vutran** [vutran/dext#98]
When using the clipboard functionality, it is hard to know if it had actually been executed. We need some sort of indicator that an item has been copied to the clipboard.

**Comment by vutran** [comment]
We can use the native [desktop notifcations API](http://electron.atom.io/docs/tutorial/desktop-environment-integration/#notifications-windows-linux-macos) for this.

**Comment by z3t0** [comment]
> When using the clipboard functionality

What clipboard functionality is this referring to? I'm new to this project so don't really know what that means

**Comment by vutran** [comment]
@z3t0 Users have the ability to copy items to the clipboard.

Example: using the calculator plugin, <kbd>cmd</kbd> + <kbd>c</kbd> would copy the answer to the desktop's clipboard.

More information can be found [here](https://github.com/vutran/dext/blob/develop/docs/PLUGINS.md#textcopy).

**Comment by z3t0** [comment]
Ahh I see, thank you for the explanation

**Comment by Magellol** [comment]
Merged in #152 🎉
